### ISSUE TITLE
can you add automatic optimal threshold number

### ISSUE THREAD

**Issue by ganbaaelmer** [pedrofrodenas/image-thresholding-OCR#1]
python adaptativeThreshold.py -i images/hh.jpg -t 50

> is optimal threshold due to high resolution is 50. Let's binarize the image using 50 as threshold.
How to know this number is 50?
I need to automatic function to generate this number.
Because OCR process is all automatic. 
We need to know this number automatically. 
Please give us suggestion. 
Need automatic function about this number

**Comment by pedrofrodenas** [comment]
> python adaptativeThreshold.py -i images/hh.jpg -t 50
> 
> > is optimal threshold due to high resolution is 50. Let's binarize the image using 50 as threshold.
> > How to know this number is 50?
> > I need to automatic function to generate this number.
> > Because OCR process is all automatic.
> > We need to know this number automatically.
> > Please give us suggestion.
> > Need automatic function about this number

I used 50 as threshold through trial and error. The paper not covers how to choose an optimal threshold but I think it depends on if you have hard contrast lines or softer gradient lines.

You could calculate the laplacian of an image and check it's variance. If the variance is hight the image is more likely to have hard contrast lines so it may help you to find an optimal or automatic threshold.
